
# Site settings

title: Statelis
url: "https://www.statelis.ch"
baseurl: ""


description: >-
  AI Powered Data Integration for Bioinformatics.

email: contact@statelis.ch
phone_number: +41 (0)22 000 00 00
twitter_username: statelis
github_username:  statelis


# Build settings

#plugins:
#  - jekyll-sitemap
#  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

